### ISSUE TITLE
update to high pass filter circuit to restore FM bass with YM2612

### ISSUE THREAD

**Issue by svirant** [Fujix1/NanoDrive6#2]
C23/C28 (left FM channel) and C24/C27 (right FM channel) in their current values of 1uf removes a lot of the bass from the FM signal when using the YM2612. Replacing all 4 of these with 22uf alters the high pass filter so that bass from the FM is kept in tact.  Not saying this is mandatory of course, but it made a huge difference to my ears when changed. At least 6uf is recommended but 10uf or 22uf would work nicely since they are standard values easy to find.

You could also update C18 in the PSG circuit to something higher (10uf or 22uf) so that it's high pass filter value is closer to 1uf like the MegaDrive. I don't think you will really notice a difference with the PSG as the lowest note it can produce is around 122hz anyways.

**Comment by Fujix1** [comment]
![524d89183adf7c711d8870f7183da99b](https://github.com/user-attachments/assets/82a1f2ec-b1eb-4278-a422-363209102e1a)
I added 22uFs, I don't see any difference for the lower frequency.
https://e2j.net/temp/1uf.wav
https://e2j.net/temp/23uf.wav

**Comment by svirant** [comment]
My apologies. Is this using a YM3438 or YM2612?  My use case has been for the YM2612, and that being said the math checks out OK for the YM3438 with 1uf.

Default Circuit with 1uf:
YM3438: 1uf in series with 1uf with 13k resistor = 24Hz high pass
YM2612: 1uf in series with 1uf with 2.2k resistor =  144Hz high pass -> cuts bass

Modified Circuit with 22uf:
YM3438: 22uf in series with 22uf with 13k resistor = 1Hz high pass
YM2612: 22uf in series with 22uf with 2.2k resistor =  6.6Hz high pass

Here is my math:
<img width="650" alt="math" src="https://github.com/user-attachments/assets/40d3e299-b3d8-4f3b-9005-0d895742965e">

Capacitors of at least 6uf would also give a 24Hz high pass for the YM2612.  The only reason I chose 22uf is because in series that gets you close to the 10uf that is used on the Megadrive.

**Comment by Fujix1** [comment]
I tested with YM2612 now. comparison between 1uf and 22uf.
![download](https://github.com/user-attachments/assets/c147bb9a-0117-47d5-a499-4985a6378d26)

I'll update my schematics. Thank you for the info.

**Comment by svirant** [comment]
You're very welcome!! I enjoy your NanoDrive6 very much and happy to help!
